version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: literalura
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: literalura
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

